[package]
name = "plane-system"
version = "0.1.0"
authors = ["Ibiyemi Abiodun <ibiyemi@intulon.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cxx = "0.5"
pretty_env_logger = "0.4"
log = "0.4.11"
anyhow = "1.0"
mavlink = { features = ["ardupilotmega", "uavionix", "icarous"], git = "https://github.com/laptou/rust-mavlink" }
num-traits = "0.2"
num-derive = "0.3"
simplebgc = { git = "https://github.com/laptou/simplebgc-rs" }
futures = "0.3.5"
bytes = "0.6"
tokio = { version = "0.2", features = ["full"] }
serde = "1.0"
ctrlc = "3.1"
warp = "0.2"
serde_millis = "0.1.1"
structopt = "0.3"
clap = "2"
config = "0.10.1"
rustyline = "6.3.0"
async-trait = "0.1.41"

[build-dependencies]
cxx-build = "0.5"
