[package]
name = "plane-system"
version = "0.1.0"
authors = ["Ibiyemi Abiodun <ibiyemi@intulon.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
smol = "1.0.0"
crossbeam = "0.7.3"
cxx = "0.4.2"
tide = "0.13.0"
pretty_env_logger = "0.4.0"
log = "0.4.11"
anyhow = "1.0.32"
mavlink = { features = ["ardupilotmega", "uavionix", "icarous"], version = "0.8.5" }
num-traits = "0.2.12"
smol-timeout = "0.5.0"
simplebgc = { git = "https://github.com/laptou/simplebgc-rs" }
num-derive = "0.3.2"
async-trait = "0.1.40"
futures = "0.3.5"
crc-any = "2.3.5"

[build-dependencies]
cxx-build = "0.4.2"
