[package]
name = "ps-client"
version = "1.0.0"
edition = "2021"

[dependencies]
async-trait = { workspace = true }
tokio-util = { workspace = true }
tokio = { workspace = true }
anyhow = { workspace = true }
flume = { workspace = true }
log = { workspace = true }
